//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BicycleStation
{
    using System;
    using System.Collections.Generic;
    
    public partial class dock
    {
        public int dock_id { get; set; }
        public int station_id { get; set; }
        public int holds_bicycle { get; set; }
        public byte is_locked { get; set; }
    }
}
